### ISSUE TITLE
show information

### ISSUE THREAD

**Issue by charlie884** [eduardoarandah/wordpress-crud-example#2]
Hi, nice example, but i have a question, how can i show the information in the frontend?

**Comment by eduardoarandah** [comment]
There's many options, just copy the php code here
https://github.com/eduardoarandah/wordpress-crud-example/blob/master/sinetiks-schools/schools-list.php

and put into any of those:

- in your theme using the hierarchy
- in a custom page template
- in a widget
- in a rest api

https://developer.wordpress.org/themes/basics/template-hierarchy/
